name: Auto Create and Merge Pull Request

on:
  push:
    branches-ignore:
      - "main"

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          title: "Automated PR: ${{ github.ref_name }}"
          body: "This is an automated pull request created from branch ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge pull request
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
